import Head from 'next/head'
import { Col, Row, Navbar, Container, Offcanvas, Nav,  Form, NavDropdown, FormControl, Button, } from 'react-bootstrap'
import styles from '../styles/Home.module.css'
import HomeVideo from "../components/Videoplayer/index"
import Link from 'next/link'
export default function Home() {

  return (
    <div>
      <Head>
        <title>WasteNot: -WantNot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Beth+Ellen&family=Righteous&display=swap" rel="stylesheet" /> */}
      </Head>

      <main className={styles.main}>
      <Container className={styles.container}>
      <HomeVideo/>
      <Navbar expand={false}>
        <Container fluid>
        <Navbar.Toggle aria-controls="offcanvasNavbar" />
            <Navbar.Brand href="#"><img className={styles.brand} src="https://i.ibb.co/MV46RZx/Recycle-icon-by-rudezstudio-2-580x386-copy.png"/></Navbar.Brand>
            <Navbar.Offcanvas
            id="offcanvasNavbar"
            aria-labelledby="offcanvasNavbarLabel"
            placement="start"
            className={styles.offcanvas}
            >
        <Offcanvas.Header closeButton className={styles.offcanvasHeader}>
        <Offcanvas.Title id="offcanvasNavbarLabel">WasteNot: WantNot</Offcanvas.Title>
        <img className={styles.brand} src="https://i.ibb.co/MV46RZx/Recycle-icon-by-rudezstudio-2-580x386-copy.png"/>
        </Offcanvas.Header>
      <Offcanvas.Body>
        <Nav className="justify-content-end flex-grow-1 pe-3">
          <Nav.Link className={styles.navLink} href="#action1">About Us</Nav.Link>
          <Nav.Link className={styles.navLink} href="#action2">Food waste matters!</Nav.Link>
          <Nav.Link className={styles.navLink} href="#action2">Manage, Reduce, Donate!</Nav.Link>
          <Nav.Link className={styles.navLink} href="/donations">Find Food Banks!</Nav.Link>
          <Nav.Link className={styles.navLink} href="/">Register</Nav.Link>
        </Nav>
      
      </Offcanvas.Body>
    </Navbar.Offcanvas>
  </Container>
</Navbar>        

<Row className={styles.row}>
        <div className={styles.heading}>
          <Col className={styles.headingT} xs={{span: 8}}>
            <Row className={styles.headingR}>
              <span className={styles.span}><strong>Waste</strong>Not:</span>
            </Row>
            <Row className={styles.headingU}>
              <span className={styles.span}><strong>Want</strong>Not<strong>!</strong></span>

            </Row>
          </Col>
          <Col className={styles.headingS} xs={{span: 4}}>
            <img className={styles.brandHead} src="https://i.ibb.co/MV46RZx/Recycle-icon-by-rudezstudio-2-580x386-copy.png"/>
          </Col>


        </div>

</Row>
        <Row className={styles.login}>
        <a className={styles.a} href = "/api/auth/login">
        <Button className={styles.loginBtn}>Login / Signup</Button>
        </a>
        </Row>
        <Row className={styles.footer}></Row>
        </Container>
      </main>

    </div>
  )
}
